on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    
    steps:
    - name: Remotely Start Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /mnt/apps
          if [ -d profile-v4 ]
          then
            cd profile-v4
            git pull
          else
            git clone https://github.com/p-sw/profile-v4
            cd profile-v4
          fi
          npm install && npm run build && ( PORT=3002 pm2 restart profile-v4 || PORT=3002 pm2 start "node build" --name profile-v4 )
