on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.8.1
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Send Built File to Server
      uses: appleboy/scp-action@v0.1.4
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        source: "build"
        target: "/mnt/apps/profile-v4"
    - name: Remotely Start Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /mnt/apps/profile-v4
          export PM2_HOME=/home/psw/.pm2
          /usr/local/bin/pm2 restart profile-v4 || /usr/local/bin/pm2 start "node build" --name profile-v4
          
